/**
 * Lote de subasta de ejemplo — DATOS INVENTADOS.
 *
 * Existe para que el prorrateo, los índices y las políticas se ejerciten contra
 * algo que se parezca a la realidad: montos que no dividen redondo, mezcla de
 * gradadoras, deportes y TCG, y alguna carta sin foto y sin publicar.
 *
 * Cuando llegue el Excel real del lote de Alt de agosto de 2026, se reemplaza
 * este archivo y nada más: el seed no sabe de dónde salen los datos.
 */

export type DemoCard = {
  type: "graded_card" | "raw_card" | "sealed_box";
  category: "sports" | "tcg";
  sportOrGame: string;
  playerOrCharacter: string;
  brand: string;
  setName: string;
  year: number;
  cardNumber: string;
  variant?: string;
  serialNumbered?: string;
  isRookie?: boolean;
  isAutograph?: boolean;
  isPatch?: boolean;
  language: string;
  gradingCompany: "PSA" | "BGS" | "CGC" | "SGC" | "none";
  grade?: number;
  gradeLabel?: string;
  certNumber?: string;
  hammerPrice: string;
  marketValue: string;
  listPrice?: string;
  minPrice?: string;
  isPublished?: boolean;
};

export const DEMO_ACQUISITION = {
  platform: "alt" as const,
  reference: "DEMO-ALT-2026-08",
  purchasedAt: "2026-08-14",
  currency: "USD",
  /** Comisión de la casa de subastas. */
  buyerPremium: "556.32",
  /** 3.3% sobre martillo más comisión, el default de la sección 13. */
  cardFee: "111.26",
  shippingIntl: "85.00",
  courierVe: "62.40",
  customsVe: "203.15",
  otherCosts: "0",
  notes: "Lote de demostración. Sustituir por el Excel real del lote de Alt de agosto.",
};

export const DEMO_CARDS: readonly DemoCard[] = [
  {
    type: "graded_card",
    category: "tcg",
    sportOrGame: "One Piece",
    playerOrCharacter: "Monkey D. Luffy",
    brand: "Bandai",
    setName: "Carrying On His Will",
    year: 2025,
    cardNumber: "OP13-118",
    variant: "Manga Rare",
    language: "JP",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "118442901",
    hammerPrice: "383.00",
    marketValue: "520.00",
    listPrice: "545.00",
    minPrice: "470.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "tcg",
    sportOrGame: "One Piece",
    playerOrCharacter: "Roronoa Zoro",
    brand: "Bandai",
    setName: "Emperors in the New World",
    year: 2024,
    cardNumber: "OP09-051",
    variant: "Alt Art",
    language: "JP",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "115003422",
    hammerPrice: "212.50",
    marketValue: "285.00",
    listPrice: "299.00",
    minPrice: "255.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "NBA",
    playerOrCharacter: "Victor Wembanyama",
    brand: "Panini",
    setName: "Prizm",
    year: 2023,
    cardNumber: "136",
    variant: "Silver Prizm",
    isRookie: true,
    language: "EN",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "104558871",
    hammerPrice: "640.00",
    marketValue: "790.00",
    listPrice: "849.00",
    minPrice: "720.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "NBA",
    playerOrCharacter: "Anthony Edwards",
    brand: "Panini",
    setName: "Select",
    year: 2020,
    cardNumber: "44",
    variant: "Concourse",
    isRookie: true,
    language: "EN",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "98221043",
    hammerPrice: "97.77",
    marketValue: "128.00",
    listPrice: "139.00",
    minPrice: "115.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "Soccer",
    playerOrCharacter: "Lamine Yamal",
    brand: "Topps",
    setName: "Chrome UEFA Club Competitions",
    year: 2023,
    cardNumber: "112",
    variant: "Refractor",
    serialNumbered: "15/99",
    isRookie: true,
    language: "EN",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "110774320",
    hammerPrice: "1450.33",
    marketValue: "1690.00",
    listPrice: "1795.00",
    minPrice: "1550.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "tcg",
    sportOrGame: "Pokémon",
    playerOrCharacter: "Charizard",
    brand: "The Pokémon Company",
    setName: "Obsidian Flames",
    year: 2023,
    cardNumber: "223",
    variant: "Special Illustration Rare",
    language: "EN",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "101993877",
    hammerPrice: "268.00",
    marketValue: "340.00",
    listPrice: "365.00",
    minPrice: "310.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "tcg",
    sportOrGame: "Pokémon",
    playerOrCharacter: "Pikachu",
    brand: "The Pokémon Company",
    setName: "Celebrations",
    year: 2021,
    cardNumber: "005",
    variant: "Holo",
    language: "EN",
    gradingCompany: "BGS",
    grade: 9.5,
    gradeLabel: "Gem Mint",
    certNumber: "0019338477",
    hammerPrice: "74.25",
    marketValue: "95.00",
    listPrice: "109.00",
    minPrice: "88.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "NFL",
    playerOrCharacter: "C.J. Stroud",
    brand: "Panini",
    setName: "Prizm",
    year: 2023,
    cardNumber: "301",
    variant: "Base",
    isRookie: true,
    language: "EN",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "105663214",
    hammerPrice: "133.90",
    marketValue: "168.00",
    listPrice: "185.00",
    minPrice: "150.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "NFL",
    playerOrCharacter: "Patrick Mahomes",
    brand: "Panini",
    setName: "Donruss Optic",
    year: 2017,
    cardNumber: "177",
    variant: "Rated Rookie",
    isRookie: true,
    language: "EN",
    gradingCompany: "PSA",
    grade: 9,
    gradeLabel: "Mint",
    certNumber: "88450211",
    hammerPrice: "310.00",
    marketValue: "375.00",
    listPrice: "399.00",
    minPrice: "345.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "MLB",
    playerOrCharacter: "Paul Skenes",
    brand: "Topps",
    setName: "Chrome",
    year: 2024,
    cardNumber: "USC12",
    variant: "Refractor",
    isRookie: true,
    isAutograph: true,
    language: "EN",
    gradingCompany: "PSA",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "112009873",
    hammerPrice: "845.00",
    marketValue: "1020.00",
    listPrice: "1099.00",
    minPrice: "930.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "MLB",
    playerOrCharacter: "Ronald Acuña Jr.",
    brand: "Topps",
    setName: "Chrome",
    year: 2018,
    cardNumber: "193",
    variant: "Base",
    isRookie: true,
    language: "EN",
    gradingCompany: "SGC",
    grade: 10,
    gradeLabel: "Gem Mint",
    certNumber: "SGC7741220",
    hammerPrice: "188.44",
    marketValue: "225.00",
    listPrice: "249.00",
    minPrice: "205.00",
    isPublished: true,
  },
  {
    type: "graded_card",
    category: "tcg",
    sportOrGame: "One Piece",
    playerOrCharacter: "Portgas D. Ace",
    brand: "Bandai",
    setName: "Memorial Collection",
    year: 2024,
    cardNumber: "EB01-006",
    variant: "Parallel",
    language: "JP",
    gradingCompany: "CGC",
    grade: 9.5,
    gradeLabel: "Mint+",
    certNumber: "4118220034",
    hammerPrice: "126.10",
    marketValue: "155.00",
    isPublished: false,
  },
  {
    type: "graded_card",
    category: "sports",
    sportOrGame: "NBA",
    playerOrCharacter: "Luka Dončić",
    brand: "Panini",
    setName: "Prizm",
    year: 2018,
    cardNumber: "280",
    variant: "Base",
    isRookie: true,
    language: "EN",
    gradingCompany: "PSA",
    grade: 9,
    gradeLabel: "Mint",
    certNumber: "94002118",
    hammerPrice: "402.66",
    marketValue: "460.00",
    isPublished: false,
  },
  {
    type: "raw_card",
    category: "tcg",
    sportOrGame: "Pokémon",
    playerOrCharacter: "Umbreon",
    brand: "The Pokémon Company",
    setName: "Evolving Skies",
    year: 2021,
    cardNumber: "215",
    variant: "Alt Art",
    language: "EN",
    gradingCompany: "none",
    hammerPrice: "515.00",
    marketValue: "640.00",
    isPublished: false,
  },
  {
    type: "sealed_box",
    category: "tcg",
    sportOrGame: "One Piece",
    playerOrCharacter: "—",
    brand: "Bandai",
    setName: "Royal Blood",
    year: 2024,
    cardNumber: "OP-06",
    language: "JP",
    gradingCompany: "none",
    hammerPrice: "96.05",
    marketValue: "130.00",
    isPublished: false,
  },
] as const;
